openapi: 3.0.3
info:
  title: Chat Service
  description: Service for chat app, a Goa teaser
  version: "1.0"
servers:
- url: http://172.25.0.3:8000
paths:
  /chatroom/{id}:
    get:
      tags:
      - chatapi
      summary: getchat chatapi
      operationId: chatapi#getchat
      parameters:
      - name: id
        in: path
        description: room id
        required: true
        schema:
          type: integer
          description: room id
          example: 7331539213984418867
          format: int64
        example: 2589955657104534163
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoaChatCollection'
              example:
              - Chat: Aut numquam similique.
                Id: 5625972352155160976
                Member: Nihil debitis magnam dolorem qui praesentium iure.
                PostDt: "1985-11-21T12:48:29Z"
                RoomName: Eveniet voluptas quod qui.
                UserId: Rem voluptates nam voluptatem rerum rerum neque.
              - Chat: Aut numquam similique.
                Id: 5625972352155160976
                Member: Nihil debitis magnam dolorem qui praesentium iure.
                PostDt: "1985-11-21T12:48:29Z"
                RoomName: Eveniet voluptas quod qui.
                UserId: Rem voluptates nam voluptatem rerum rerum neque.
              - Chat: Aut numquam similique.
                Id: 5625972352155160976
                Member: Nihil debitis magnam dolorem qui praesentium iure.
                PostDt: "1985-11-21T12:48:29Z"
                RoomName: Eveniet voluptas quod qui.
                UserId: Rem voluptates nam voluptatem rerum rerum neque.
              - Chat: Aut numquam similique.
                Id: 5625972352155160976
                Member: Nihil debitis magnam dolorem qui praesentium iure.
                PostDt: "1985-11-21T12:48:29Z"
                RoomName: Eveniet voluptas quod qui.
                UserId: Rem voluptates nam voluptatem rerum rerum neque.
      security:
      - api_key_header_Authorization: []
components:
  schemas:
    GoaChat:
      type: object
      properties:
        Chat:
          type: string
          description: chat
          example: Voluptas dicta totam.
        Id:
          type: integer
          description: room id
          example: 3084490717507266567
          format: int64
        Member:
          type: string
          description: member
          example: Reiciendis delectus iusto sit aut accusamus.
        PostDt:
          type: string
          example: "1989-04-17T01:01:42Z"
          format: date-time
        RoomName:
          type: string
          description: room name
          example: Molestias dolorem soluta quo itaque.
        UserId:
          type: string
          description: user id
          example: Natus fuga laboriosam error inventore.
      description: All chat
      example:
        Chat: Soluta eius aut quidem dolorum in aspernatur.
        Id: 6638991917400390848
        Member: Rerum aut iusto.
        PostDt: "1998-04-05T09:47:38Z"
        RoomName: Aperiam numquam quibusdam dolor quasi impedit.
        UserId: Debitis et.
      required:
      - Id
      - UserId
      - RoomName
      - Member
      - Chat
      - PostDt
    GoaChatCollection:
      type: array
      items:
        $ref: '#/components/schemas/GoaChat'
      example:
      - Chat: Aut numquam similique.
        Id: 5625972352155160976
        Member: Nihil debitis magnam dolorem qui praesentium iure.
        PostDt: "1985-11-21T12:48:29Z"
        RoomName: Eveniet voluptas quod qui.
        UserId: Rem voluptates nam voluptatem rerum rerum neque.
      - Chat: Aut numquam similique.
        Id: 5625972352155160976
        Member: Nihil debitis magnam dolorem qui praesentium iure.
        PostDt: "1985-11-21T12:48:29Z"
        RoomName: Eveniet voluptas quod qui.
        UserId: Rem voluptates nam voluptatem rerum rerum neque.
      - Chat: Aut numquam similique.
        Id: 5625972352155160976
        Member: Nihil debitis magnam dolorem qui praesentium iure.
        PostDt: "1985-11-21T12:48:29Z"
        RoomName: Eveniet voluptas quod qui.
        UserId: Rem voluptates nam voluptatem rerum rerum neque.
  securitySchemes:
    api_key_header_Authorization:
      type: apiKey
      description: Secures endpoint by requiring an API key.
      name: Authorization
      in: header
tags:
- name: chatapi
  description: The service performs get chat.
